// Central product catalog — single source of truth for all pages
// Edit here to update products across Shop, Dashboard, New Arrivals, On Sale, and Product pages.

export interface Product {
  id: number
  slug: string
  name: string
  brand: string
  category: string
  price: string
  priceNum: number
  originalPrice: string
  discount: string
  rating: number
  stock: number
  status: 'Active' | 'Draft' | 'Out of Stock'
  image: string
  description: string
  type: 'new-arrival' | 'top-selling' | 'sale' | 'regular'
  createdAt: string
}

export const allProducts: Product[] = [
  // ── T-Shirts ──────────────────────────────────────────────────────────────
  { id: 1, slug: 't-shirt-with-tape-details', name: 'T-shirt with Tape Details', brand: 'Shop.co', category: 'T-Shirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.5, stock: 142, status: 'Active', image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&q=80', description: 'A premium crewneck T-shirt featuring contrast tape details along the shoulders and sleeves. Made from 100% breathable cotton for all-day comfort.', type: 'new-arrival', createdAt: '2024-01-12' },
  { id: 2, slug: 'sleeve-striped-t-shirt', name: 'Sleeve Striped T-shirt', brand: 'Shop.co', category: 'T-Shirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '-19%', rating: 4.5, stock: 204, status: 'Active', image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&q=80', description: 'A sporty striped T-shirt with contrast colour sleeves. Great for casual outings or layering under a jacket.', type: 'new-arrival', createdAt: '2024-01-20' },
  { id: 3, slug: 'courage-graphic-t-shirt', name: 'Courage Graphic T-shirt', brand: 'Shop.co', category: 'T-Shirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.0, stock: 0, status: 'Out of Stock', image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80', description: 'Bold typographic print on a relaxed-fit tee. The oversized design keeps things comfortable yet on-trend.', type: 'top-selling', createdAt: '2024-02-05' },
  { id: 4, slug: 'pocket-crewneck-tee', name: 'Pocket Crewneck Tee', brand: 'Shop.co', category: 'T-Shirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '-21%', rating: 4.2, stock: 78, status: 'Active', image: 'https://images.unsplash.com/photo-1554568218-0f1715e72254?w=600&q=80', description: 'A classic chest-pocket crewneck tee cut from soft jersey cotton. Minimalist and timeless.', type: 'sale', createdAt: '2024-02-18' },
  { id: 5, slug: 'classic-white-v-neck-tee', name: 'Classic White V-Neck Tee', brand: 'Shop.co', category: 'T-Shirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.6, stock: 310, status: 'Active', image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&q=80', description: 'An essential wardrobe staple. Soft, lightweight V-neck tee that pairs with everything from jeans to chinos.', type: 'regular', createdAt: '2024-03-01' },
  { id: 6, slug: 'oversized-drop-shoulder-tee', name: 'Oversized Drop-Shoulder Tee', brand: 'Shop.co', category: 'T-Shirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '-18%', rating: 4.3, stock: 55, status: 'Active', image: 'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=600&q=80', description: 'Contemporary oversized silhouette with dropped shoulders and a relaxed hem. Perfect for streetwear styling.', type: 'sale', createdAt: '2024-03-10' },
  { id: 7, slug: 'tie-dye-festival-tee', name: 'Tie-Dye Festival Tee', brand: 'Shop.co', category: 'T-Shirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 3.8, stock: 42, status: 'Active', image: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=600&q=80', description: 'Hand-dyed tie-dye pattern on a heavyweight cotton tee. No two pieces are exactly the same.', type: 'regular', createdAt: '2024-03-18' },
  { id: 8, slug: 'long-sleeve-ribbed-tee', name: 'Long Sleeve Ribbed Tee', brand: 'Shop.co', category: 'T-Shirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '-18%', rating: 4.7, stock: 90, status: 'Active', image: 'https://images.unsplash.com/photo-1622470953794-aa9c70b0fb9d?w=600&q=80', description: 'A slim-fit long sleeve tee in a ribbed fabric that hugs the body. Ideal for layering or wearing alone.', type: 'sale', createdAt: '2024-03-25' },
  { id: 9, slug: 'vintage-washed-band-tee', name: 'Vintage Washed Band Tee', brand: 'Shop.co', category: 'T-Shirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.4, stock: 38, status: 'Active', image: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=600&q=80', description: 'Acid-washed vintage finish on a relaxed tee with an abstract front graphic. Retro vibes guaranteed.', type: 'regular', createdAt: '2024-04-02' },

  // ── Shirts ────────────────────────────────────────────────────────────────
  { id: 10, slug: 'checkered-shirt', name: 'Checkered Shirt', brand: 'Shop.co', category: 'Shirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.5, stock: 56, status: 'Active', image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80', description: 'A timeless checkered shirt tailored from soft brushed cotton. Classic collar and regular fit — works for casual or smart-casual occasions.', type: 'new-arrival', createdAt: '2024-01-18' },
  { id: 11, slug: 'vertical-striped-shirt', name: 'Vertical Striped Shirt', brand: 'Shop.co', category: 'Shirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '-9%', rating: 5.0, stock: 33, status: 'Active', image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&q=80', description: 'Sophisticated vertical-striped poplin shirt in a slim cut. Tucked in for meetings or untucked for weekends.', type: 'top-selling', createdAt: '2024-02-01' },
  { id: 12, slug: 'oxford-button-down-shirt', name: 'Oxford Button-Down Shirt', brand: 'Shop.co', category: 'Shirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '-15%', rating: 4.6, stock: 71, status: 'Active', image: 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=600&q=80', description: 'Classic Oxford-weave cotton button-down with a button-down collar. A menswear icon that never goes out of style.', type: 'sale', createdAt: '2024-02-20' },
  { id: 13, slug: 'linen-summer-shirt', name: 'Linen Summer Shirt', brand: 'Shop.co', category: 'Shirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.3, stock: 102, status: 'Active', image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&q=80', description: 'Lightweight linen shirt with a relaxed Cuban collar. Breathable and perfect for warm-weather dressing.', type: 'regular', createdAt: '2024-03-05' },
  { id: 14, slug: 'flannel-plaid-shirt', name: 'Flannel Plaid Shirt', brand: 'Shop.co', category: 'Shirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '-16%', rating: 4.1, stock: 44, status: 'Active', image: 'https://images.unsplash.com/photo-1587559070757-f72a388edbba?w=600&q=80', description: 'Classic flannel plaid in a mid-weight brushed cotton. A fall and winter wardrobe essential.', type: 'sale', createdAt: '2024-03-14' },
  { id: 15, slug: 'denim-western-shirt', name: 'Denim Western Shirt', brand: 'Shop.co', category: 'Shirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.4, stock: 28, status: 'Active', image: 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=600&q=80', description: 'Stone-washed denim shirt with classic Western yoke detailing. Wear as a shirt or an over-layer.', type: 'regular', createdAt: '2024-03-22' },
  { id: 16, slug: 'slim-fit-poplin-shirt', name: 'Slim-Fit Poplin Shirt', brand: 'Shop.co', category: 'Shirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '-17%', rating: 4.7, stock: 60, status: 'Active', image: 'https://images.unsplash.com/photo-1563630423918-b58f07336ac5?w=600&q=80', description: 'Crisp poplin cotton in a tailored slim fit. Ideal for office wear, dressed up with a blazer or solo.', type: 'new-arrival', createdAt: '2024-04-08' },

  // ── Jeans ─────────────────────────────────────────────────────────────────
  { id: 17, slug: 'skinny-fit-jeans', name: 'Skinny Fit Jeans', brand: 'Shop.co', category: 'Jeans', price: '₹1', priceNum: 1, originalPrice: '', discount: '-8%', rating: 3.5, stock: 87, status: 'Active', image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80', description: 'Classic skinny fit jeans from stretch denim. Hugs the leg from hip to ankle. Available in multiple washes.', type: 'new-arrival', createdAt: '2024-01-14' },
  { id: 18, slug: 'faded-skinny-jeans', name: 'Faded Skinny Jeans', brand: 'Shop.co', category: 'Jeans', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.5, stock: 72, status: 'Active', image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&q=80', description: 'Trendy faded-wash skinny jeans with whiskered front and faded back pockets. A lived-in look.', type: 'top-selling', createdAt: '2024-02-14' },
  { id: 19, slug: 'straight-cut-raw-denim', name: 'Straight Cut Raw Denim', brand: 'Shop.co', category: 'Jeans', price: '₹1', priceNum: 1, originalPrice: '', discount: '-10%', rating: 4.6, stock: 49, status: 'Active', image: 'https://images.unsplash.com/photo-1582552938357-32b906df40cd?w=600&q=80', description: 'Unwashed raw selvedge denim in a classic straight cut. Gets better with every wear as it fades uniquely to you.', type: 'sale', createdAt: '2024-02-28' },
  { id: 20, slug: 'relaxed-tapered-jeans', name: 'Relaxed Tapered Jeans', brand: 'Shop.co', category: 'Jeans', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.2, stock: 65, status: 'Active', image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&q=80', description: 'Roomy in the thigh and tapered toward the ankle. A modern fit that sits between skinny and straight.', type: 'regular', createdAt: '2024-03-08' },
  { id: 21, slug: 'distressed-ripped-jeans', name: 'Distressed Ripped Jeans', brand: 'Shop.co', category: 'Jeans', price: '₹1', priceNum: 1, originalPrice: '', discount: '-11%', rating: 4.0, stock: 38, status: 'Active', image: 'https://images.unsplash.com/photo-1555689502-c4b22d76c56f?w=600&q=80', description: 'Heavily distressed jeans with knee rips and frayed hems. The ultimate in casual-cool denim.', type: 'sale', createdAt: '2024-03-19' },
  { id: 22, slug: 'wide-leg-jeans', name: 'Wide Leg Jeans', brand: 'Shop.co', category: 'Jeans', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.4, stock: 55, status: 'Active', image: 'https://images.unsplash.com/photo-1602810319250-a663f0af2f75?w=600&q=80', description: 'High-waisted wide-leg silhouette cut from a soft denim blend. Fashion-forward and comfortable all day.', type: 'new-arrival', createdAt: '2024-04-01' },

  // ── Shorts ────────────────────────────────────────────────────────────────
  { id: 23, slug: 'loose-fit-bermuda-shorts', name: 'Loose Fit Bermuda Shorts', brand: 'Shop.co', category: 'Shorts', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 3.0, stock: 19, status: 'Draft', image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600&q=80', description: 'Relaxed Bermuda shorts with deep side pockets. Made from lightweight twill that keeps you cool in the heat.', type: 'top-selling', createdAt: '2024-02-10' },
  { id: 24, slug: 'chino-shorts', name: 'Chino Shorts', brand: 'Shop.co', category: 'Shorts', price: '₹1', priceNum: 1, originalPrice: '', discount: '-17%', rating: 4.1, stock: 88, status: 'Active', image: 'https://images.unsplash.com/photo-1565079080184-61c0e7604f5e?w=600&q=80', description: 'Smart chino shorts in a mid-length cut. Versatile enough for the beach or a casual lunch out.', type: 'sale', createdAt: '2024-03-02' },
  { id: 25, slug: 'athletic-running-shorts', name: 'Athletic Running Shorts', brand: 'Shop.co', category: 'Shorts', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.5, stock: 120, status: 'Active', image: 'https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=600&q=80', description: 'Lightweight quick-dry fabric with a built-in liner. Reflective details for evening runs. 5-inch inseam.', type: 'regular', createdAt: '2024-03-20' },
  { id: 26, slug: 'denim-cutoff-shorts', name: 'Denim Cutoff Shorts', brand: 'Shop.co', category: 'Shorts', price: '₹1', priceNum: 1, originalPrice: '', discount: '-19%', rating: 3.9, stock: 45, status: 'Active', image: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&q=80', description: 'Classic denim cutoffs with frayed raw hem. The quintessential summer short.', type: 'sale', createdAt: '2024-04-05' },

  // ── Dresses ───────────────────────────────────────────────────────────────
  { id: 27, slug: 'floral-wrap-dress', name: 'Floral Wrap Dress', brand: 'Shop.co', category: 'Dresses', price: '₹1', priceNum: 1, originalPrice: '', discount: '-19%', rating: 4.7, stock: 62, status: 'Active', image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80', description: 'A flattering wrap silhouette in a bold floral print. V-neckline, tie waist, and a midi length that works for any occasion.', type: 'new-arrival', createdAt: '2024-02-22' },
  { id: 28, slug: 'linen-sundress', name: 'Linen Sundress', brand: 'Shop.co', category: 'Dresses', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.4, stock: 85, status: 'Active', image: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&q=80', description: 'Breezy linen sundress with adjustable straps and side pockets. Light and effortless summer dressing.', type: 'regular', createdAt: '2024-03-07' },
  { id: 29, slug: 'cocktail-slip-dress', name: 'Cocktail Slip Dress', brand: 'Shop.co', category: 'Dresses', price: '₹1', priceNum: 1, originalPrice: '', discount: '-15%', rating: 4.8, stock: 30, status: 'Active', image: 'https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=600&q=80', description: 'Satin-finish slip dress with a subtle bias cut. Elegant for evening wear, pair with strappy heels.', type: 'sale', createdAt: '2024-03-17' },
  { id: 30, slug: 'maxi-boho-dress', name: 'Maxi Boho Dress', brand: 'Shop.co', category: 'Dresses', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.3, stock: 47, status: 'Active', image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&q=80', description: 'Floor-length dress with embroidered bodice and billowy skirt. Perfect for summer festivals and beach days.', type: 'regular', createdAt: '2024-04-11' },

  // ── Pants ─────────────────────────────────────────────────────────────────
  { id: 31, slug: 'slim-chinos', name: 'Slim Chinos', brand: 'Shop.co', category: 'Pants', price: '₹1', priceNum: 1, originalPrice: '', discount: '-15%', rating: 4.5, stock: 93, status: 'Active', image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&q=80', description: 'Slim-fit chino pants in a stretch cotton twill. Smart enough for the office, comfortable enough for the weekend.', type: 'sale', createdAt: '2024-02-08' },
  { id: 32, slug: 'cargo-utility-pants', name: 'Cargo Utility Pants', brand: 'Shop.co', category: 'Pants', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.2, stock: 74, status: 'Active', image: 'https://images.unsplash.com/photo-1509551388413-e18d0ac5d495?w=600&q=80', description: 'Functional cargo pants with six pockets and a relaxed straight leg. Built for adventure.', type: 'regular', createdAt: '2024-03-12' },
  { id: 33, slug: 'jogger-sweatpants', name: 'Jogger Sweatpants', brand: 'Shop.co', category: 'Pants', price: '₹1', priceNum: 1, originalPrice: '', discount: '-17%', rating: 4.6, stock: 115, status: 'Active', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80', description: 'Soft French terry joggers with elasticated waistband and cuffs. The ultimate loungewear-to-streetwear pant.', type: 'sale', createdAt: '2024-03-26' },
  { id: 34, slug: 'wide-leg-trousers', name: 'Wide Leg Trousers', brand: 'Shop.co', category: 'Pants', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.3, stock: 41, status: 'Active', image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&q=80', description: 'High-waisted wide-leg trousers in a flowing woven fabric. A sophisticated take on relaxed suiting.', type: 'new-arrival', createdAt: '2024-04-15' },

  // ── Jackets ───────────────────────────────────────────────────────────────
  { id: 35, slug: 'denim-jacket', name: 'Classic Denim Jacket', brand: 'Shop.co', category: 'Jackets', price: '₹1', priceNum: 1, originalPrice: '', discount: '-15%', rating: 4.7, stock: 58, status: 'Active', image: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=600&q=80', description: 'A wardrobe cornerstone. Classic denim trucker jacket with chest pockets and adjustable button cuffs.', type: 'sale', createdAt: '2024-02-16' },
  { id: 36, slug: 'bomber-jacket', name: 'Bomber Jacket', brand: 'Shop.co', category: 'Jackets', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.5, stock: 36, status: 'Active', image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80', description: 'MA-1 style bomber in a premium nylon shell with ribbed collar, cuffs, and hem. Iconic silhouette.', type: 'regular', createdAt: '2024-03-04' },
  { id: 37, slug: 'leather-biker-jacket', name: 'Leather Biker Jacket', brand: 'Shop.co', category: 'Jackets', price: '₹1', priceNum: 1, originalPrice: '', discount: '-16%', rating: 4.9, stock: 22, status: 'Active', image: 'https://images.unsplash.com/photo-1520975954732-35dd22299614?w=600&q=80', description: 'Genuine lamb leather biker jacket with asymmetric zip, lapel collar, and quilted panels. A statement piece.', type: 'sale', createdAt: '2024-03-23' },
  { id: 38, slug: 'puffer-parka', name: 'Puffer Parka', brand: 'Shop.co', category: 'Jackets', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.6, stock: 48, status: 'Active', image: 'https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=600&q=80', description: 'Long-line puffer parka with a detachable hood, storm cuffs, and two-way zip. Winter-ready.', type: 'new-arrival', createdAt: '2024-04-18' },

  // ── Hoodies ───────────────────────────────────────────────────────────────
  { id: 39, slug: 'pullover-hoodie', name: 'Pullover Hoodie', brand: 'Shop.co', category: 'Hoodies', price: '₹1', priceNum: 1, originalPrice: '', discount: '-17%', rating: 4.6, stock: 132, status: 'Active', image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&q=80', description: 'Classic heavyweight pullover hoodie in a midweight brushed fleece. Kangaroo pocket and adjustable drawcord.', type: 'sale', createdAt: '2024-02-25' },
  { id: 40, slug: 'zip-up-hoodie', name: 'Zip-Up Hoodie', brand: 'Shop.co', category: 'Hoodies', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.4, stock: 89, status: 'Active', image: 'https://images.unsplash.com/photo-1620799139507-2a76f79a2f4d?w=600&q=80', description: 'Full-zip hoodie in a soft cotton-polyester blend. Two side pockets and a lined hood for added warmth.', type: 'regular', createdAt: '2024-03-09' },
  { id: 41, slug: 'oversized-fleece-hoodie', name: 'Oversized Fleece Hoodie', brand: 'Shop.co', category: 'Hoodies', price: '₹1', priceNum: 1, originalPrice: '', discount: '-17%', rating: 4.8, stock: 67, status: 'Active', image: 'https://images.unsplash.com/photo-1615397349754-cfa2066a298e?w=600&q=80', description: 'Oversized teddy-fleece hoodie with a boxy cut, extra-large hood, and front pocket. Cozy and stylish.', type: 'new-arrival', createdAt: '2024-04-03' },
  { id: 42, slug: 'cropped-hoodie', name: 'Cropped Hoodie', brand: 'Shop.co', category: 'Hoodies', price: '₹1', priceNum: 1, originalPrice: '', discount: '-16%', rating: 4.3, stock: 54, status: 'Active', image: 'https://images.unsplash.com/photo-1542219550-37153d387c27?w=600&q=80', description: 'Cropped-length hoodie that pairs perfectly with high-waisted bottoms. French terry cotton for everyday wear.', type: 'sale', createdAt: '2024-04-20' },

  // ── Skirts ────────────────────────────────────────────────────────────────
  { id: 43, slug: 'pleated-midi-skirt', name: 'Pleated Midi Skirt', brand: 'Shop.co', category: 'Skirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '-16%', rating: 4.5, stock: 63, status: 'Active', image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&q=80', description: 'Elegant pleated midi skirt in a fluid crepe fabric. Knee-to-calf length with an elasticated waistband.', type: 'new-arrival', createdAt: '2024-03-03' },
  { id: 44, slug: 'denim-mini-skirt', name: 'Denim Mini Skirt', brand: 'Shop.co', category: 'Skirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.2, stock: 77, status: 'Active', image: 'https://images.unsplash.com/photo-1609505848912-b7c3b8b4beda?w=600&q=80', description: 'A-line denim mini skirt with button-front detailing. A 90s classic reimagined for today.', type: 'regular', createdAt: '2024-03-29' },
  { id: 45, slug: 'satin-bias-skirt', name: 'Satin Bias-Cut Skirt', brand: 'Shop.co', category: 'Skirts', price: '₹1', priceNum: 1, originalPrice: '', discount: '-17%', rating: 4.6, stock: 35, status: 'Active', image: 'https://images.unsplash.com/photo-1599999905949-47748e6fa4e8?w=600&q=80', description: 'Satin bias-cut skirt with an asymmetric hem. Luxe finish, floaty drape — perfect for evenings out.', type: 'sale', createdAt: '2024-04-12' },

  // ── Tops ──────────────────────────────────────────────────────────────────
  { id: 46, slug: 'ribbed-crop-top', name: 'Ribbed Crop Top', brand: 'Shop.co', category: 'Tops', price: '₹1', priceNum: 1, originalPrice: '', discount: '-17%', rating: 4.3, stock: 140, status: 'Active', image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=600&q=80', description: 'Stretchy ribbed fabric in a cropped silhouette. A versatile layering piece that works with everything.', type: 'sale', createdAt: '2024-03-06' },
  { id: 47, slug: 'sleeveless-knit-top', name: 'Sleeveless Knit Top', brand: 'Shop.co', category: 'Tops', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.4, stock: 92, status: 'Active', image: 'https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=600&q=80', description: 'Fine-gauge knit tank top with a scoop neck. Lightweight and breathable for warm-weather layering.', type: 'regular', createdAt: '2024-03-25' },
  { id: 48, slug: 'off-shoulder-top', name: 'Off-Shoulder Top', brand: 'Shop.co', category: 'Tops', price: '₹1', priceNum: 1, originalPrice: '', discount: '-16%', rating: 4.5, stock: 68, status: 'Active', image: 'https://images.unsplash.com/photo-1566206091558-7f218b696731?w=600&q=80', description: 'Elasticated off-shoulder neckline on a flowy top. Effortlessly romantic styling for summer occasions.', type: 'new-arrival', createdAt: '2024-04-09' },
  { id: 49, slug: 'tie-front-blouse', name: 'Tie-Front Blouse', brand: 'Shop.co', category: 'Tops', price: '₹1', priceNum: 1, originalPrice: '', discount: '-17%', rating: 4.6, stock: 51, status: 'Active', image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80', description: 'Tie-front blouse in a lightweight woven fabric with floral embroidery on the collar. Feminine and elegant.', type: 'sale', createdAt: '2024-04-21' },
  { id: 50, slug: 'camisole-top', name: 'Camisole Top', brand: 'Shop.co', category: 'Tops', price: '₹1', priceNum: 1, originalPrice: '', discount: '', rating: 4.1, stock: 200, status: 'Active', image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&q=80', description: 'Silk-touch satin camisole with adjustable straps. Wear as a standalone or as a chic layering piece.', type: 'regular', createdAt: '2024-04-28' },
]

// Convenience helpers
export const getProductBySlug = (slug: string): Product | undefined =>
  allProducts.find((p) => p.slug === slug)

export const getProductsByCategory = (category: string): Product[] =>
  category === 'All' ? allProducts : allProducts.filter((p) => p.category === category)

export const getNewArrivals = (): Product[] =>
  allProducts.filter((p) => p.type === 'new-arrival' || p.type === 'regular')

export const getSaleProducts = (): Product[] =>
  allProducts.filter((p) => p.discount !== '')
